### ISSUE TITLE
Allow users to upload their own set of strings via JSON

### ISSUE THREAD

**Issue by KyleTaylorLange** [KyleTaylorLange/StringTensionCalculator#16]
The program shall allow users to upload their own JSON file matching the internal JSON format with new string series and sets. This would not be saved to a server; it would just allow the user to use their custom values in the client.

If duplicate values are entered, they should override the existing values. The use case would be if string manufacturing changes to the point that the unit weights have changed dramatically.

**Comment by m-lamotte** [comment]
Reference: https://github.com/KyleTaylorLange/StringTensionCalculator/pull/20

Note that the enhancement I implemented in the pull request above does not actually provide the ability for a user to upload strings via JSON, but rather a pop-up interface that allows for the addition (or continuous modification) of a set of a maximum of eight (8) strings.
