### ISSUE TITLE
String Table not loading on GitHub Pages site.

### ISSUE THREAD

**Issue by KyleTaylorLange** [KyleTaylorLange/StringTensionCalculator#17]
The main table is not loading on the live version of the web app on [GitHub Pages](https://kyletaylorlange.github.io/StringTensionCalculator/). 

The console shows the following error message:
```
Uncaught (in promise) Error: Status :: 404
    getJson https://kyletaylorlange.github.io/StringTensionCalculator/dist/src/static/Utilities.js:29
```

**Comment by m-lamotte** [comment]
Issue resolved in merge of branch `json-fetch-fix`.
